global:
  registry: localhost:5000
  version: latest

services:
  - name: api-gateway
    replicaCount: 1
    port: 8080
    service:
      type: NodePort
      port: 8080
      nodePort: 30000
  - name: auth
    replicaCount: 1
    port: 9090
    service:
      type: ClusterIP
      port: 9090
  - name: device
    replicaCount: 1
    port: 9200
    service:
      type: ClusterIP
      port: 9200
  - name: voice
    replicaCount: 1
    port: 9100
    service:
      type: ClusterIP
      port: 9100
  - name: web
    replicaCount: 1
    port: 3000
    service:
      type: NodePort
      port: 3000
      nodePort: 30001 